In [1]:
import numpy as np
import numpy as np
import pandas as pd

In [2]:
data = np.array([1, 2, 1, 2, 3, 4, 1])

In [3]:
data

array([1, 2, 1, 2, 3, 4, 1])

In [7]:
np.exp(data)
np.divide (np.exp(data), np.exp(data).sum())

array([0.0278465 , 0.07569463, 0.0278465 , 0.07569463, 0.20575935,
       0.55931189, 0.0278465 ])

In [12]:
import numpy as np

l = np.array([-1, 0, 1])

def softmax(l):
    exp = np.exp(l)
    return np.divide(exp, exp.sum())

softmax(l)

array([0.09003057, 0.24472847, 0.66524096])