In [3]:
import numpy as np
import torch

In [4]:
x = torch.rand(3, 2)

In [5]:
x

tensor([[0.3228, 0.5422],
        [0.8479, 0.0397],
        [0.8418, 0.8932]])

In [6]:
x.size()

torch.Size([3, 2])

In [7]:
y = torch.ones(x.size())

In [8]:
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [9]:
z = x + y

In [10]:
z

tensor([[1.3228, 1.5422],
        [1.8479, 1.0397],
        [1.8418, 1.8932]])

In [11]:
z.add(1) # 新

tensor([[2.3228, 2.5422],
        [2.8479, 2.0397],
        [2.8418, 2.8932]])

In [12]:
z.add_(1)

tensor([[2.3228, 2.5422],
        [2.8479, 2.0397],
        [2.8418, 2.8932]])

In [14]:
z.size()

torch.Size([3, 2])

In [15]:
z.resize_(2, 3)

tensor([[2.3228, 2.5422, 2.8479],
        [2.0397, 2.8418, 2.8932]])

In [16]:
b = np.random.rand(4, 2)

In [17]:
b

array([[0.32910809, 0.47300662],
       [0.93411026, 0.94417012],
       [0.8601461 , 0.79190151],
       [0.88151982, 0.47348982]])

In [18]:
t = torch.from_numpy(b)

In [19]:
t

tensor([[0.3291, 0.4730],
        [0.9341, 0.9442],
        [0.8601, 0.7919],
        [0.8815, 0.4735]], dtype=torch.float64)

In [21]:
t.numpy()

array([[0.32910809, 0.47300662],
       [0.93411026, 0.94417012],
       [0.8601461 , 0.79190151],
       [0.88151982, 0.47348982]])