In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(100)])

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(100,)

In [6]:
x.size

100

In [15]:
y = np.array([[i for i in range(10)], [i for i in range(10)]])

In [16]:
y

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
y.dtype

dtype('int64')

In [18]:
y.shape

(2, 10)

In [19]:
y.size

20

In [20]:
z = np.array([1, 2.2, 3.0], dtype=np.int64)

In [21]:
z

array([1, 2, 3])

In [22]:
np.save('z_array', z)

In [23]:
z1 = np.load('z_array.npy')

In [24]:
z1

array([1, 2, 3])