In [3]:
import numpy as np

In [4]:
x = np.zeros((3, 3))

In [5]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
x.dtype

dtype('float64')

In [7]:
x1 = np.ones((2, 2))

In [8]:
x1

array([[1., 1.],
       [1., 1.]])

In [9]:
x5 = np.full((4, 4), 5)

In [10]:
x5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [11]:
eye = np.eye(10)

In [12]:
eye

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
np.diag([10, 20])

array([[10,  0],
       [ 0, 20]])

In [14]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [17]:
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [18]:
x = np.arange(20)

In [19]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
x.reshape((4, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [21]:
x.reshape((20, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [22]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.linspace(10, 30, 25, endpoint=False).reshape(5, 5)

array([[10. , 10.8, 11.6, 12.4, 13.2],
       [14. , 14.8, 15.6, 16.4, 17.2],
       [18. , 18.8, 19.6, 20.4, 21.2],
       [22. , 22.8, 23.6, 24.4, 25.2],
       [26. , 26.8, 27.6, 28.4, 29.2]])

In [24]:
np.random.random((3, 3))

array([[0.50342329, 0.79887691, 0.30784514],
       [0.4667841 , 0.60480563, 0.79438328],
       [0.07166063, 0.84061313, 0.40390574]])

In [28]:
np.random.randint(1, 5, (2, 2))

array([[3, 2],
       [4, 3]])

In [30]:
np.random.normal(0, 0.1, size=(3, 3))

array([[-0.0767724 ,  0.03311788,  0.07425889],
       [ 0.06206057, -0.08461595, -0.13513399],
       [-0.14151982,  0.03332511,  0.02556805]])