In [1]:
import numpy as np

In [2]:
x = np.array([i for i in range(10)])

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[8]

8

In [5]:
x[8] = -8

In [6]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7, -8,  9])

In [9]:
x1 = np.arange(1, 10).reshape(3, 3)

In [10]:
x1[0, 1]

2

In [11]:
x1[0, 0] = 100

In [12]:
x1

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [13]:
y = np.array([i for i in range(5)])

In [14]:
y

array([0, 1, 2, 3, 4])

In [18]:
y = np.delete(y, [2, 3])

In [19]:
y

array([ 0,  1, -8,  9])

In [20]:
y = np.arange(1, 10).reshape(3, 3)

In [21]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.delete(y, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
np.delete(y, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
x = np.array([i for i in range(10)])

In [25]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x = np.append(x, 10)

In [28]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x.view()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
x = np.append(x, [[i for i in range(11)]])

In [34]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10])

In [35]:
x.shape

(22,)

In [47]:
x = x.reshape(11, 2)

In [48]:
x = np.append(x, [[i] for i in range(11)], axis=1)

In [40]:
[[i] for i in range(11)]

[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]

In [46]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  1,  2,  3,  4,  5,
        6,  7,  8,  9, 10])

In [49]:
x

array([[ 0,  1,  0],
       [ 2,  3,  1],
       [ 4,  5,  2],
       [ 6,  7,  3],
       [ 8,  9,  4],
       [10,  0,  5],
       [ 1,  2,  6],
       [ 3,  4,  7],
       [ 5,  6,  8],
       [ 7,  8,  9],
       [ 9, 10, 10]])

In [50]:
x = np.insert(x, 1, 0, axis=1)

In [51]:
x

array([[ 0,  0,  1,  0],
       [ 2,  0,  3,  1],
       [ 4,  0,  5,  2],
       [ 6,  0,  7,  3],
       [ 8,  0,  9,  4],
       [10,  0,  0,  5],
       [ 1,  0,  2,  6],
       [ 3,  0,  4,  7],
       [ 5,  0,  6,  8],
       [ 7,  0,  8,  9],
       [ 9,  0, 10, 10]])

In [52]:
x = np.array([[3, 4], [5, 6]])

In [53]:
x

array([[3, 4],
       [5, 6]])

In [56]:
x

array([[3, 4],
       [5, 6]])

In [57]:
y = np.array([1, 2])

In [58]:
x = np.vstack((x, y))

In [59]:
x

array([[3, 4],
       [5, 6],
       [1, 2]])

In [61]:
x = np.hstack((y, x.reshape(2, 1)))

ValueError: cannot reshape array of size 6 into shape (2,1)

In [62]:
x

array([[3, 4],
       [5, 6],
       [1, 2]])

In [63]:
w = np.hstack((x, np.array([1, 2, 3]).reshape(3, 1)))

In [64]:
w

array([[3, 4, 1],
       [5, 6, 2],
       [1, 2, 3]])