In [1]:
import numpy as np

1. ndarray[start:end]
2. ndarray[start:]
3. ndarray[:end]

In [2]:
x = np.arange(1, 21).reshape(4, 5)

In [3]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
x[1:4, 2:5]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20]])

In [5]:
x[2:, 3:]

array([[14, 15],
       [19, 20]])

In [6]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
z = np.copy(x[2:, 2:])

In [8]:
z

array([[13, 14, 15],
       [18, 19, 20]])