In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5, 5)

In [3]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
x[x>20]

array([21, 22, 23, 24])

In [5]:
x[x<5]

array([0, 1, 2, 3, 4])

In [6]:
x[x % 2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [7]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

In [12]:
x = np.random.randint(1, 11, size=(10,))

In [13]:
x

array([ 1, 10,  5,  3,  1, 10,  2,  2,  7,  2])

In [14]:
np.sort(x)

array([ 1,  1,  2,  2,  2,  3,  5,  7, 10, 10])

In [15]:
x = np.random.randint(1, 11, size=(5, 5))

In [16]:
x

array([[10,  1,  7,  6,  2],
       [10,  7,  5,  8,  1],
       [ 9,  1,  1,  7,  8],
       [ 6,  4,  2,  6,  1],
       [ 6, 10,  1,  9,  7]])

In [17]:
np.sort(x, axis=0)

array([[ 6,  1,  1,  6,  1],
       [ 6,  1,  1,  6,  1],
       [ 9,  4,  2,  7,  2],
       [10,  7,  5,  8,  7],
       [10, 10,  7,  9,  8]])

In [18]:
np.sort(x, axis=1)

array([[ 1,  2,  6,  7, 10],
       [ 1,  5,  7,  8, 10],
       [ 1,  1,  7,  8,  9],
       [ 1,  2,  4,  6,  6],
       [ 1,  6,  7,  9, 10]])