In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])

In [3]:
x + y

array([2, 4, 6, 8])

In [4]:
np.add(x, y)

array([2, 4, 6, 8])

In [5]:
x - y

array([0, 0, 0, 0])

In [6]:
np.subtract(x, y)

array([0, 0, 0, 0])

In [7]:
x * y

array([ 1,  4,  9, 16])

In [8]:
np.multiply(x, y)

array([ 1,  4,  9, 16])

In [9]:
x / y 

array([1., 1., 1., 1.])

In [10]:
np.divide(x, y)

array([1., 1., 1., 1.])

In [11]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([5, 6, 7, 8]).reshape(2, 2)

In [13]:
x * y

array([[ 5, 12],
       [21, 32]])

In [14]:
np.sqrt(x * y)

array([[2.23606798, 3.46410162],
       [4.58257569, 5.65685425]])

In [15]:
np.exp(x)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [16]:
np.power(x, 3)

array([[ 1,  8],
       [27, 64]])

In [17]:
x.mean()

2.5

In [18]:
x.std()

1.118033988749895

In [20]:
np.median(x)

2.5

In [22]:
x.max()

4

In [23]:
x.min()

1

In [24]:
x - 1

array([[0, 1],
       [2, 3]])

In [25]:
x = np.arange(3)

In [26]:
x

array([0, 1, 2])

In [27]:
y = np.arange(9).reshape(3, 3)

In [28]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])